services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "13306:3306" # 호스트 포트:컨테이너 포트
    environment:
      MYSQL_ROOT_PASSWORD: 'hhplus'   # Root 사용자 비밀번호
      MYSQL_USER: hhplus              # 생성할 사용자 이름
      MYSQL_PASSWORD: 'hhplus'        # 생성할 사용자 비밀번호
    volumes:
      - ./data:/var/lib/mysql   # 데이터 저장소
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 초기화 스크립트
    restart: always                   # 컨테이너 재시작 정책
