services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'hhplus'
      MYSQL_USER: hhplus
      MYSQL_PASSWORD: hhplus
      MYSQL_DATABASE: hhplus
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
