TRUNCATE TABLE ISSUED_COUPON;
TRUNCATE TABLE COUPON_INVENTORY;
TRUNCATE TABLE COUPON;
TRUNCATE TABLE PRODUCT_INVENTORY;
TRUNCATE TABLE PRODUCT;
TRUNCATE TABLE USER;
TRUNCATE TABLE WALLET;
TRUNCATE TABLE WALLET_HISTORY;