DELETE FROM USER WHERE true;
DELETE FROM WALLET WHERE true;
DELETE FROM WALLET_HISTORY WHERE true;
DELETE FROM COUPON WHERE true;
DELETE FROM COUPON_INVENTORY WHERE true;
DELETE FROM ISSUED_COUPON WHERE true;
